labels:
  - name: "priority: critical"
    color: "d73a4a"
    description: "Critical issue that blocks development or production"
  - name: "priority: high"
    color: "f85149"
    description: "High priority issue that should be addressed soon"
  - name: "priority: medium"
    color: "fbca04"
    description: "Medium priority issue"
  - name: "priority: low"
    color: "0e8a16"
    description: "Low priority issue"
  - name: "type: bug"
    color: "d73a4a"
    description: "Something isn't working"
  - name: "type: enhancement"
    color: "a2eeef"
    description: "New feature or request"
  - name: "type: refactor"
    color: "7057ff"
    description: "Code change that neither fixes a bug nor adds a feature"
  - name: "type: documentation"
    color: "0075ca"
    description: "Documentation only changes"
  - name: "type: testing"
    color: "28a745"
    description: "Adding or updating tests"
  - name: "type: performance"
    color: "ff8c00"
    description: "Performance improvements"
  - name: "type: security"
    color: "d93f0b"
    description: "Security improvements or fixes"
  - name: "status: needs-triage"
    color: "ffccd5"
    description: "Issue needs to be reviewed and categorized"
  - name: "status: ready"
    color: "0e8a16"
    description: "Issue is ready to be worked on"
  - name: "status: in-progress"
    color: "1d76db"
    description: "Issue is currently being worked on"
  - name: "status: blocked"
    color: "d93f0b"
    description: "Issue is blocked by another issue or dependency"
  - name: "status: needs-review"
    color: "fbca04"
    description: "Issue needs code review"
  - name: "status: needs-testing"
    color: "28a745"
    description: "Issue needs testing before completion"
  - name: "architecture: domain"
    color: "6f42c1"
    description: "Changes to domain layer"
  - name: "architecture: application"
    color: "6f42c1"
    description: "Changes to application layer"
  - name: "architecture: adapters"
    color: "6f42c1"
    description: "Changes to adapters layer"
  - name: "architecture: shared"
    color: "6f42c1"
    description: "Changes to shared utilities"
  - name: "component: authentication"
    color: "1d76db"
    description: "Authentication and authorization"
  - name: "component: workouts"
    color: "1d76db"
    description: "Workout management"
  - name: "component: users"
    color: "1d76db"
    description: "User management"
  - name: "component: http-client"
    color: "1d76db"
    description: "HTTP client and API communication"
  - name: "component: storage"
    color: "1d76db"
    description: "Data storage and persistence"
  - name: "component: validation"
    color: "1d76db"
    description: "Data validation and schemas"
  - name: "component: logging"
    color: "1d76db"
    description: "Logging and monitoring"
  - name: "component: testing"
    color: "1d76db"
    description: "Testing framework and utilities"
  - name: "effort: small"
    color: "0e8a16"
    description: "Small change, less than 1 day"
  - name: "effort: medium"
    color: "fbca04"
    description: "Medium change, 1-3 days"
  - name: "effort: large"
    color: "ff8c00"
    description: "Large change, 3-7 days"
  - name: "effort: epic"
    color: "d93f0b"
    description: "Epic change, more than 1 week"
  - name: "breaking-change"
    color: "d93f0b"
    description: "Breaking change that requires migration"
  - name: "migration-required"
    color: "fbca04"
    description: "Migration guide needed for users"
  - name: "quality: technical-debt"
    color: "ff8c00"
    description: "Technical debt that should be addressed"
  - name: "quality: code-review"
    color: "28a745"
    description: "Code review required"
  - name: "quality: testing"
    color: "28a745"
    description: "Testing improvements needed"
  - name: "release: next"
    color: "1d76db"
    description: "Targeted for next release"
  - name: "release: future"
    color: "6f42c1"
    description: "Targeted for future release"
  - name: "release: patch"
    color: "0e8a16"
    description: "Patch version change"
  - name: "release: minor"
    color: "fbca04"
    description: "Minor version change"
  - name: "release: major"
    color: "d93f0b"
    description: "Major version change"
