/**
 * Error Codes
 * Centralized error codes for consistent error handling across the application
 */

export const ERROR_CODES = {
  // Authentication Errors (1000-1999)
  AUTH_FAILED: 'AUTH_1001',
  AUTH_TOKEN_EXPIRED: 'AUTH_1002',
  AUTH_TOKEN_INVALID: 'AUTH_1003',
  AUTH_TOKEN_REFRESH_FAILED: 'AUTH_1004',
  AUTH_NO_ADAPTER_FOUND: 'AUTH_1005',
  AUTH_USER_NOT_FOUND: 'AUTH_1006',
  AUTH_INVALID_CREDENTIALS: 'AUTH_1007',
  AUTH_WEB_AUTH_FAILED: 'AUTH_1008',
  AUTH_REFRESH_NOT_SUPPORTED: 'AUTH_1009',
  AUTH_LOGIN_FAILED: 'AUTH_1010',
  AUTH_TOKEN_NOT_FOUND: 'AUTH_1011',
  AUTH_VERIFICATION_TOKEN_MISSING: 'AUTH_1012',
  AUTH_COOKIE_MISSING: 'AUTH_1013',
  AUTH_USER_DATA_MISSING: 'AUTH_1014',

  // User Errors (3000-3999)
  USER_FETCH_FAILED: 'USER_3001',
  USER_NOT_FOUND: 'USER_3002',

  // Workout Errors (2000-2999)
  WORKOUT_CREATION_FAILED: 'WORKOUT_2001',
  WORKOUT_UPLOAD_FAILED: 'WORKOUT_2002',
  WORKOUT_DELETION_FAILED: 'WORKOUT_2003',
  WORKOUT_NOT_FOUND: 'WORKOUT_2004',
  WORKOUT_VALIDATION_FAILED: 'WORKOUT_2005',
  WORKOUT_STRUCTURE_INVALID: 'WORKOUT_2006',
  WORKOUT_FILE_INVALID: 'WORKOUT_2007',
  WORKOUT_NAME_INVALID: 'WORKOUT_2008',
  WORKOUT_DESCRIPTION_INVALID: 'WORKOUT_2009',
  WORKOUT_TAGS_INVALID: 'WORKOUT_2010',
  WORKOUT_METADATA_INVALID: 'WORKOUT_2011',
  WORKOUT_REPOSITORY_ERROR: 'WORKOUT_2012',

  // Network Errors (4000-4999)
  NETWORK_TIMEOUT: 'NETWORK_4001',
  NETWORK_CONNECTION_FAILED: 'NETWORK_4002',
  NETWORK_REQUEST_FAILED: 'NETWORK_4003',
  NETWORK_RESPONSE_INVALID: 'NETWORK_4004',
  NETWORK_RATE_LIMITED: 'NETWORK_4005',
  NETWORK_SERVER_ERROR: 'NETWORK_4006',
  NETWORK_SERVICE_UNAVAILABLE: 'NETWORK_4007',

  // Validation Errors (5000-5999)
  VALIDATION_FAILED: 'VALIDATION_5001',
  VALIDATION_REQUIRED_FIELD: 'VALIDATION_5002',
  VALIDATION_INVALID_FORMAT: 'VALIDATION_5003',
  VALIDATION_OUT_OF_RANGE: 'VALIDATION_5004',

  // Configuration Errors (6000-6999)
  CONFIG_INVALID: 'CONFIG_6001',
  CONFIG_MISSING: 'CONFIG_6002',
  CONFIG_INVALID_URL: 'CONFIG_6003',

  // Internal Errors (9000-9999)
  INTERNAL_ERROR: 'INTERNAL_9001',
  UNKNOWN_ERROR: 'UNKNOWN_9999',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

/**
 * Error Messages
 * Standardized error messages for consistent user experience
 */
export const ERROR_MESSAGES = {
  [ERROR_CODES.AUTH_FAILED]: 'Authentication failed',
  [ERROR_CODES.AUTH_TOKEN_EXPIRED]: 'Authentication token has expired',
  [ERROR_CODES.AUTH_TOKEN_INVALID]: 'Authentication token is invalid',
  [ERROR_CODES.AUTH_TOKEN_REFRESH_FAILED]:
    'Failed to refresh authentication token',
  [ERROR_CODES.AUTH_NO_ADAPTER_FOUND]:
    'No suitable authentication method found',
  [ERROR_CODES.AUTH_USER_NOT_FOUND]: 'User not found after authentication',
  [ERROR_CODES.AUTH_INVALID_CREDENTIALS]: 'Invalid credentials provided',
  [ERROR_CODES.AUTH_WEB_AUTH_FAILED]: 'Web authentication failed',
  [ERROR_CODES.AUTH_REFRESH_NOT_SUPPORTED]:
    'Token refresh not supported for this authentication method',
  [ERROR_CODES.AUTH_LOGIN_FAILED]: 'Login failed',
  [ERROR_CODES.AUTH_TOKEN_NOT_FOUND]: 'Authentication token not found',
  [ERROR_CODES.AUTH_VERIFICATION_TOKEN_MISSING]:
    'Request verification token missing',
  [ERROR_CODES.AUTH_COOKIE_MISSING]: 'Required authentication cookie missing',
  [ERROR_CODES.AUTH_USER_DATA_MISSING]: 'User data missing from response',

  [ERROR_CODES.WORKOUT_CREATION_FAILED]: 'Failed to create workout',
  [ERROR_CODES.WORKOUT_UPLOAD_FAILED]: 'Failed to upload workout',
  [ERROR_CODES.WORKOUT_DELETION_FAILED]: 'Failed to delete workout',
  [ERROR_CODES.WORKOUT_NOT_FOUND]: 'Workout not found',
  [ERROR_CODES.WORKOUT_VALIDATION_FAILED]: 'Workout validation failed',
  [ERROR_CODES.WORKOUT_STRUCTURE_INVALID]: 'Workout structure is invalid',
  [ERROR_CODES.WORKOUT_FILE_INVALID]: 'Workout file is invalid',
  [ERROR_CODES.WORKOUT_NAME_INVALID]: 'Workout name is invalid',
  [ERROR_CODES.WORKOUT_DESCRIPTION_INVALID]: 'Workout description is invalid',
  [ERROR_CODES.WORKOUT_TAGS_INVALID]: 'Workout tags are invalid',
  [ERROR_CODES.WORKOUT_METADATA_INVALID]: 'Workout metadata is invalid',
  [ERROR_CODES.WORKOUT_REPOSITORY_ERROR]: 'Workout repository error',

  [ERROR_CODES.USER_FETCH_FAILED]: 'Failed to get user',
  [ERROR_CODES.USER_NOT_FOUND]: 'User not found',

  [ERROR_CODES.NETWORK_TIMEOUT]: 'Network request timed out',
  [ERROR_CODES.NETWORK_CONNECTION_FAILED]: 'Network connection failed',
  [ERROR_CODES.NETWORK_REQUEST_FAILED]: 'Network request failed',
  [ERROR_CODES.NETWORK_RESPONSE_INVALID]: 'Invalid network response',
  [ERROR_CODES.NETWORK_RATE_LIMITED]: 'Rate limit exceeded',
  [ERROR_CODES.NETWORK_SERVER_ERROR]: 'Server error occurred',
  [ERROR_CODES.NETWORK_SERVICE_UNAVAILABLE]: 'Service temporarily unavailable',

  [ERROR_CODES.VALIDATION_FAILED]: 'Validation failed',
  [ERROR_CODES.VALIDATION_REQUIRED_FIELD]: 'Required field is missing',
  [ERROR_CODES.VALIDATION_INVALID_FORMAT]: 'Invalid format',
  [ERROR_CODES.VALIDATION_OUT_OF_RANGE]: 'Value is out of valid range',

  [ERROR_CODES.CONFIG_INVALID]: 'Invalid configuration',
  [ERROR_CODES.CONFIG_MISSING]: 'Missing configuration',
  [ERROR_CODES.CONFIG_INVALID_URL]: 'Invalid URL in configuration',

  [ERROR_CODES.INTERNAL_ERROR]: 'Internal error occurred',
  [ERROR_CODES.UNKNOWN_ERROR]: 'An unknown error occurred',
} as const;

/**
 * HTTP Status Codes Mapping
 * Maps error codes to appropriate HTTP status codes
 */
export const ERROR_STATUS_CODES = {
  [ERROR_CODES.AUTH_FAILED]: 401,
  [ERROR_CODES.AUTH_TOKEN_EXPIRED]: 401,
  [ERROR_CODES.AUTH_TOKEN_INVALID]: 401,
  [ERROR_CODES.AUTH_TOKEN_REFRESH_FAILED]: 401,
  [ERROR_CODES.AUTH_NO_ADAPTER_FOUND]: 500,
  [ERROR_CODES.AUTH_USER_NOT_FOUND]: 404,
  [ERROR_CODES.AUTH_INVALID_CREDENTIALS]: 401,
  [ERROR_CODES.AUTH_WEB_AUTH_FAILED]: 401,
  [ERROR_CODES.AUTH_REFRESH_NOT_SUPPORTED]: 501,
  [ERROR_CODES.AUTH_LOGIN_FAILED]: 401,
  [ERROR_CODES.AUTH_TOKEN_NOT_FOUND]: 401,
  [ERROR_CODES.AUTH_VERIFICATION_TOKEN_MISSING]: 400,
  [ERROR_CODES.AUTH_COOKIE_MISSING]: 401,
  [ERROR_CODES.AUTH_USER_DATA_MISSING]: 502,

  [ERROR_CODES.USER_FETCH_FAILED]: 500,
  [ERROR_CODES.USER_NOT_FOUND]: 404,

  [ERROR_CODES.WORKOUT_CREATION_FAILED]: 500,
  [ERROR_CODES.WORKOUT_UPLOAD_FAILED]: 500,
  [ERROR_CODES.WORKOUT_DELETION_FAILED]: 500,
  [ERROR_CODES.WORKOUT_NOT_FOUND]: 404,
  [ERROR_CODES.WORKOUT_VALIDATION_FAILED]: 400,
  [ERROR_CODES.WORKOUT_STRUCTURE_INVALID]: 400,
  [ERROR_CODES.WORKOUT_FILE_INVALID]: 400,
  [ERROR_CODES.WORKOUT_NAME_INVALID]: 400,
  [ERROR_CODES.WORKOUT_DESCRIPTION_INVALID]: 400,
  [ERROR_CODES.WORKOUT_TAGS_INVALID]: 400,
  [ERROR_CODES.WORKOUT_METADATA_INVALID]: 400,
  [ERROR_CODES.WORKOUT_REPOSITORY_ERROR]: 500,

  [ERROR_CODES.NETWORK_TIMEOUT]: 408,
  [ERROR_CODES.NETWORK_CONNECTION_FAILED]: 503,
  [ERROR_CODES.NETWORK_REQUEST_FAILED]: 500,
  [ERROR_CODES.NETWORK_RESPONSE_INVALID]: 502,
  [ERROR_CODES.NETWORK_RATE_LIMITED]: 429,
  [ERROR_CODES.NETWORK_SERVER_ERROR]: 500,
  [ERROR_CODES.NETWORK_SERVICE_UNAVAILABLE]: 503,

  [ERROR_CODES.VALIDATION_FAILED]: 400,
  [ERROR_CODES.VALIDATION_REQUIRED_FIELD]: 400,
  [ERROR_CODES.VALIDATION_INVALID_FORMAT]: 400,
  [ERROR_CODES.VALIDATION_OUT_OF_RANGE]: 400,

  [ERROR_CODES.CONFIG_INVALID]: 500,
  [ERROR_CODES.CONFIG_MISSING]: 500,
  [ERROR_CODES.CONFIG_INVALID_URL]: 500,

  [ERROR_CODES.INTERNAL_ERROR]: 500,
  [ERROR_CODES.UNKNOWN_ERROR]: 500,
} as const;
